/* extension error statuses */

/** $COMMENT#EN#TSDOC#SRC#CONSTS#ERRORS#STATUSES#NO_WORKSPACE_FOLDERS */
export const NO_WORKSPACE_FOLDERS = "NO_WORKSPACE_FOLDERS";
/** $COMMENT#EN#TSDOC#SRC#CONSTS#ERRORS#STATUSES#NO_TS_EXTENSION_API */
export const NO_TS_EXTENSION_API = "NO_TS_EXTENSION_API";
/** $COMMENT#EN#TSDOC#SRC#CONSTS#ERRORS#STATUSES#COMVAR_READONLY_NOT_INITIALIZED */
export const COMVAR_READONLY_NOT_INITIALIZED =
  "COMVAR_READONLY_NOT_INITIALIZED";
